bin: ~/bin
.bash_aliases: ~/.bash_aliases
.bash_profile: ~/.bash_profile
.bashrc: ~/.bashrc
.git-dispatcher: ~/.git-dispatcher
.git-flow-completion: ~/.git-flow-completion
.git-ignore: ~/.git-ignore
.gitconfig: ~/.gitconfig
.gitprompt: ~/.gitprompt
.gnupg: ~/.gnupg
.gradle/gradle.properties: ~/.gradle/gradle.properties
.inputrc: ~/.inputrc
.mvn-completion.bash: ~/.mvn-completion.bash
.ssh: ~/.ssh
.vimrc: ~/.vimrc
