bin: ~/bin
.bash_aliases: ~/.bash_aliases
.bash_profile: ~/.bash_profile
.bashrc: ~/.bashrc
.git-flow-completion: ~/.git-flow-completion
.gitconfig: ~/.gitconfig
.gitprompt: ~/.gitprompt
.gnupg: ~/.gnupg
.gradle/gradle.properties: ~/.gradle/gradle.properties
.inputrc: ~/.inputrc
.ssh: ~/.ssh
.vimrc: ~/.vimrc
