bin: ~/bin
.gitconfig: ~/.gitconfig
.gitignore-global: ~/.gitignore-global
.gnupg/gpg.conf: ~/.gnupg/gpg.conf
.m2/settings.xml: ~/.m2/settings.xml
.oh-my-zsh/themes/whiskeysierra.zsh-theme: ~/.oh-my-zsh/themes/whiskeysierra.zsh-theme
.ssh: ~/.ssh
.vimrc: ~/.vimrc
.zshrc: ~/.zshrc
